service: point-to-ukraine

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  bucket: point-to-ukraine-dev

provider:
  name: aws
  profile: personal
  runtime: nodejs10.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    BUCKET: ${self:custom.bucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  cron:
    handler: points/summarize.run
    timeout: 120
    events:
      # Invoke Lambda function every 5 minutes
      - schedule: rate(5 minutes)
  create:
    handler: points/create.create
    events:
      - http:
          path: points
          method: post
          cors: true

resources:
  Resources:
    PointsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 4
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
